version: '3.0'
services:
  server:
      image: nginx:latest
      ports:
          - "80:80"
      volumes:
          - ../service:/var/www/html
          - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
  php-fpm:
      build: ./php-fpm/
      ports:
          - "9000:9000"
      volumes:
          - ../service:/var/www/html